feat(backend): get user by id instead by username
c3pm-labs/backend pull request #4
Opened 2020-11-06 21:06 UTC by MinaBarry

2020-11-07 01:41 UTC, MinaBarry commented
Rajouter l'update du mot de passe dans la mutation.

2020-11-07 13:19 UTC, chloebourbion requested changes
can you replace `newUsername`by `username`?

2020-11-09 16:28 UTC, chloebourbion approved these changes

2020-11-09 16:30 UTC, ClementDBS approved these changes

2020-11-09 16:31 UTC, merged